wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [80, 80]
    rows: [35, 10, 10]
  refreshInterval: 1
  mods:
    feedreader:
      enabled: true
      feeds:
      - http://heise.de/developer/rss/news-atom.xml
      feedLimit: 30
      position:
        top: 0
        left: 0
        width: 1
        height: 1
      refreshInterval: 14400
