wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [80, 80]
    rows: [35, 10, 10]
  refreshInterval: 1
  mods:
    feedreader:
      enabled: true
      feeds:
      - http://heise.de/developer/rss/news-atom.xml
      feedLimit: 30
      position:
        top: 0
        left: 0
        width: 1
        height: 1
      refreshInterval: 14400
    jira:
      apiKey: "%API_KEY%"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://tonykleiber.atlassian.net"
      email: "tony.kleiber@gmail.com"
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 2
      project: "EN"
      refreshInterval: 900
      username: "%USERNAME"
      verifyServerCertificate: true
